
server:
  port: 9001

spring:
  cloud:
    config:
      server:
        git:
#          uri: file://${user.home}/start-main-config-repository
          uri: https://github.com/linzhuzai/start-main
#           uri: file://E:/GitHub/spring-cloud-start-main/start-main-config-repository/start-main-config-repository
          search-paths: start-main-config-repository
            
eureka:
  instance:
    hostname: localhost
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
      
      
#security:
#  user:
#    name: user
#    password: 258258
    
    